// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHyiiQ4xquBg31KsUdg9l0AUy2ko4HeEI',
    appId: '1:696054072898:web:3431c7846073c015b1cfdb',
    messagingSenderId: '696054072898',
    projectId: 'study-mate-1b55f',
    authDomain: 'study-mate-1b55f.firebaseapp.com',
    storageBucket: 'study-mate-1b55f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX0mXm66itn4OMZop2dE3h2jSyp9i9i10',
    appId: '1:696054072898:android:888d40f8df925811b1cfdb',
    messagingSenderId: '696054072898',
    projectId: 'study-mate-1b55f',
    storageBucket: 'study-mate-1b55f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiF_jPWI20NrvCLFgPhL4TOavJxJyf2AQ',
    appId: '1:696054072898:ios:fb0946c76d433e43b1cfdb',
    messagingSenderId: '696054072898',
    projectId: 'study-mate-1b55f',
    storageBucket: 'study-mate-1b55f.appspot.com',
    iosClientId: '696054072898-b6ipg4e8o644dbc49e4bm0mpnak4tq3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyMate',
  );
}
